### PR TITLE
Upgraded vue-data-ui with click events on mini charts

### PR DESCRIPTION
**Pull request by graphieros**
Hi,

I noticed one missing feature regarding click events on mini charts.
I upgraded the library to make this work, and implemented a usage example in your components.

Hope this fits your requirements.

Cheers

### CODE REVIEW

**Comment by TheHighestBit** [comment]
Hey,

First of all, big thanks for the awesome library! The documentation is easily some of the best I have worked with. Thanks also for implementing this feature so quickly, it's exactly what I had in mind. 

Unfortunately,  upgrading the package version seems to have also introduced an issue: 
 - The right-most bar on the sparkline is centered on the edge of the component and half of the bar is outside of it.  The issue is also present on the docs page https://vue-data-ui.graphieros.com/docs#vue-ui-sparkline

image

All the best!

**Comment by graphieros** [comment]
Thanks for your feedback:)

It seems some padding went missing in the process. I'm going to fix that.
I'm also wondering why the red bars are so high. What's are the datasets for '24h Error count' and '7d Error count' so I can reproduce ?

I'll keep you posted when I update the library.

**Comment by TheHighestBit** [comment]
Both datasets are all 0s except for the last item, which has a value of 1.  

For the 7d dataset:
```
const dataset = ref<VueUiSparklineDatasetItem[]>([]);

for (let i = 0; i < 6; i++) {
  dataset.value.push({
    value: 0,
    period: i.toString(),
  });
}

dataset.value.push({
  value: 1,
  period: "7",
});
```
It would be nice to have the zero-line at the bottom when all values are non-negative.

**Comment by graphieros** [comment]
You should be good to go now, fixed in v.2.0.11

**Comment by TheHighestBit** [comment]
Yep, seems to be working fine now. Thanks for the help!

**Pull request closed without merging**
